### PR TITLE
install heimdall during container start

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by thelamer** [comment]
Couldn't it extract as the user and avoid the chown? 

Also can we use this for some new selective chown logic ?

**Comment by aptalca** [comment]
I'm not aware of a tar option to extract as a specific user so no idea if that would have a benefit or whether it would be the same as tar xf and then chown -R.

But I tested this on a system that is affected by the chown bug and both the tar operation and the chown are completed in a split second

**Comment by thelamer** [comment]
You use s6 set id like we do with the init logic 
```
s6-setuidgid abc tar ......
```

**Comment by sparklyballs** [comment]
on slow systems, particularly sd card based systems like arm boards etc, all you're doing is swapping a slow chown for a slow unpack. 

we tried unpacking tars as abc aeons ago, there were problems, can't remember specifically what, but they were significant enough that we abandoned the idea.

**Comment by thelamer** [comment]
@sparklyballs it is a bug in overlay specific to chown: 
https://github.com/docker/for-linux/issues/388
Chown hits the files in a loop individually so overlay does COW action on every hit.
Though we should be running tar as abc here to avoid the subsequent chown.

**Comment by aptalca** [comment]
This isn't for slow systems. This is for systems affected by the overlayfs bug where the first recursive chown for that location takes several minutes. In this case, the tar unpack takes a split second on one of those systems, and the following recursive chown also takes a split second.

**Comment by sparklyballs** [comment]
back in lonix days we had to abandon using abc to unpack tars, i can't specifically remember why, but as i already said it was significant enough to have to stop it.

**Pull request merged**
